export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const ADD_ITEM = "ADD_ITEM"
export const USER = "USER"
export const USER_BUY = "USER_BUY"
export const CLEAR_CART = "CLEAR_CART"
export const PROFIL_EDIT = "PROFIL_EDIT"